/** Homepage copy for GitHub × Vercel redesign. Imported into COPY.homepage. */
export const HOMEPAGE_COPY = {
  hero: {
    eyebrow: "PROTOCOL · v1.0 · ETHEREUM MAINNET",
    headlineLine1: "Your repositories",
    headlineLine2: "are already productive.",
    headlineLine3: "Now they're",
    headlineAccent: "programmable.",
    subhead:
      "EtherBonds is a wallet that connects your GitHub account to your domain registrar. Your repositories become on-chain instruments. Your domain becomes the settlement address. Stablecoin yield flows directly to the infrastructure you already own.",
    ctaPrimary: "Connect GitHub",
    ctaSecondary: "Read the Documentation →",
    cliRow: {
      npm: "npm install @etherbonds/sdk",
      curl: "curl -fsSL etherbonds.sh | sh",
      github: "View on GitHub ↗",
    },
    mockup: {
      repo: "etherbonds/vercel",
      branch: "main",
    },
  },
  trustedBy: {
    label: "INTEGRATES WITH",
    names: [
      "github",
      "gitlab",
      "bitbucket",
      "namecheap",
      "cloudflare",
      "godaddy",
      "porkbun",
      "vercel",
      "netlify",
      "ethereum",
      "optimism",
      "base",
      "arbitrum",
    ] as const,
    caption: "Protocol-agnostic. Registrar-agnostic. Chain-agnostic.",
  },
  howItWorks: {
    label: "HOW IT WORKS",
    headline: "Three connections. One instrument.",
    subhead:
      "Connect your GitHub. Connect your domain. The protocol does the rest — indexing repository activity, generating analytics, settling yield in stablecoins to the registrar address you already control.",
    steps: [
      {
        n: "01",
        title: "Connect GitHub",
        body: "Grant read-only access to the repositories you want to instrument. Public or private — the protocol indexes both without exposing private content.",
        oauthRepos: ["acme/design-system", "acme/api-gateway", "acme/edge-runtime"],
      },
      {
        n: "02",
        title: "Connect Registrar",
        body: "Link the domain you already own — the registrar becomes the settlement address. Supported registrars include Namecheap, Cloudflare, GoDaddy, Porkbun, and any registrar compatible with the EPP protocol.",
        domainLine: "vercel.com ● CONNECTED · USDC settlement enabled",
      },
      {
        n: "03",
        title: "Issue Instrument",
        body: "Define the tenor, the yield source, and the metrics to track. The protocol writes a smart contract, indexes your repository, and begins accruing yield from the first block.",
        terminalLines: [
          "$ etherbonds issue --repo next.js --tenor 60mo --settlement vercel.com",
          "",
          "✓ Instrument deployed to 0x7a...3f",
          "✓ Settlement address verified",
          "✓ First yield accrual: block 19,284,551",
          "→ View on Etherscan",
        ],
      },
    ] as const,
  },
  repositoryInstruments: {
    label: "REPOSITORY INSTRUMENTS",
    headline: "Every commit, a cashflow.",
    body: "EtherBonds treats your repository as an economic primitive. Commits, merged pull requests, releases, downstream installs, and CI runs are all indexed, weighted, and converted into yield streams. The protocol supports three instrument tenors — 12, 36, and 60 months — each with distinct yield characteristics.",
    tenors: [
      {
        label: "12-MONTH",
        text: "Liquid, lower yield, suited for active repositories with unpredictable activity patterns.",
      },
      {
        label: "36-MONTH",
        text: "Moderate commitment, mid-tier yield, suited for repositories with established contributor bases.",
      },
      {
        label: "60-MONTH",
        text: "Long-dated, highest yield, suited for protocol-level infrastructure repositories.",
      },
    ] as const,
    cta: "See instrument specifications →",
    dashboard: {
      breadcrumb: "etherbonds ❯ instruments ❯ vercel/next.js",
      live: "LIVE",
      metrics: [
        { label: "ACCRUED YIELD", value: "$12,847.52", sub: "+2.4% this month" },
        { label: "COMMITS / WEEK", value: "127", sub: "↑ 12 vs prior" },
        { label: "NEXT SETTLEMENT", value: "15 FEB 2025", sub: "12 days" },
      ] as const,
      feed: [
        { line: "Merge: PR #8241 by @tim · +0.34 USDC", time: "2m" },
        { line: "Release: v15.2.1 tagged · +12.40 USDC", time: "4h" },
        { line: "Downstream install: 47,201 new installs · +8.91 USDC", time: "1d" },
        { line: "Settlement complete: 2,847.52 USDC → vercel.com", time: "3d" },
      ] as const,
    },
  },
  domainWallet: {
    label: "DOMAIN WALLET",
    headline: "The registrar is the bank.",
    body: "Your domain is already an address. EtherBonds treats it as a settlement address. Yield generated by your repositories is routed through programmable stablecoin rails to the wallet attached to your registrar — no bridges, no wrapped assets, no custody. Withdraw to any connected bank account or let it compound on-chain.",
    subbody:
      "The wallet is non-custodial. EtherBonds never holds your funds. Settlement happens directly between the instrument contract and the address you control.",
    pills: [
      "Non-custodial",
      "USDC native",
      "EPP-compatible",
      "Registrar-agnostic",
      "Auto-compound optional",
    ] as const,
    cta: "View supported registrars →",
    wallet: {
      title: "vercel.com — Connected Wallet",
      balance: "48,291.74",
      balanceLabel: "USDC · Available for withdrawal",
      earnings: [
        { label: "This month", value: "+12,847.52 USDC" },
        { label: "Year to date", value: "+48,291.74 USDC" },
        { label: "Lifetime", value: "+127,492.08 USDC" },
      ] as const,
      repos: [
        { name: "next.js", status: "ACTIVE", mo: "2,847 USDC/mo" },
        { name: "turborepo", status: "ACTIVE", mo: "1,204 USDC/mo" },
        { name: "vercel-ai-sdk", status: "ACTIVE", mo: "892 USDC/mo" },
      ] as const,
      withdraw: "Withdraw to bank",
      configure: "Configure routing",
    },
  },
  analyticsEngine: {
    label: "ANALYTICS ENGINE",
    headline: "Every repository is data. Every data point is yield.",
    subhead:
      "The protocol's indexer processes GitHub webhooks, package registry telemetry, and on-chain deployment signals to construct yield curves for each repository. All indexing is open-source and verifiable.",
    cards: [
      {
        title: "Commit Velocity Index",
        body: "Weighted commit frequency normalised against repository age and contributor base. Published hourly.",
      },
      {
        title: "Downstream Usage Signal",
        body: "Real-time package registry integration. Tracks installs, dependents, and transitive references across npm, PyPI, Cargo, and more.",
      },
      {
        title: "Deployment Cadence",
        body: "CI/CD webhook integration measures release frequency and deployment success rates. Correlates with long-term yield.",
      },
      {
        title: "Contributor Distribution",
        body: "Gini coefficient of contribution spread. Well-distributed repositories earn a distribution premium.",
      },
      {
        title: "Issue Resolution Latency",
        body: "Mean time to issue close. Faster resolution correlates with active maintenance and compounds yield.",
      },
      {
        title: "Fork Network Health",
        body: "Depth and activity of the fork graph. Active forks indicate ecosystem value beyond the canonical repo.",
      },
    ] as const,
  },
  stablecoinSettlement: {
    label: "SETTLEMENT",
    headline: "Stablecoin rails. Native USD.",
    body: "All yield is denominated in fully-backed, regulated stablecoins and settled directly to the wallet attached to your domain. No volatility. No conversion. No intermediaries holding funds between accrual and distribution. When your repository earns, you receive USD — delivered to the address you already control.",
    flow: [
      { node: "Repository", arrowLabel: "webhook" },
      { node: "Indexer", arrowLabel: "oracle update" },
      { node: "Instrument Contract", arrowLabel: "USDC transfer" },
      { node: "Domain Wallet", arrowLabel: "" as const },
    ] as const,
    quote:
      "Settlement is atomic. Yield is verifiable on Etherscan within the same block as repository activity.",
  },
  developerCLI: {
    label: "DEVELOPER EXPERIENCE",
    headline: "CLI-first. Config-as-code.",
    body: "Manage your instruments from the command line. Everything that can be done in the dashboard can be done with a single command. Configuration lives in .etherbonds.yml, committed to your repository alongside your source.",
    features: [
      "Issue new instruments from the terminal",
      "Preview yield projections against historical data",
      "Rotate settlement addresses without redeploying contracts",
      "Export settlement history as CSV, JSON, or on-chain transaction log",
      "Integrate with GitHub Actions for automated instrument lifecycle",
    ] as const,
    terminalTitle: "~/vercel/next.js — etherbonds",
  },
  useCases: {
    label: "USE CASES",
    headline: "Who issues instruments?",
    cards: [
      {
        label: "OPEN SOURCE MAINTAINERS",
        headline: "Capitalise on work you've already shipped.",
        body: "Maintainers of widely-used libraries finally have a mechanism to receive sustained, non-philanthropic revenue tied directly to the ongoing economic activity their code generates.",
      },
      {
        label: "PROTOCOL TEAMS",
        headline: "Turn your core repository into a treasury asset.",
        body: "Protocol DAOs can issue instruments on their canonical repositories and route settlement to a treasury multisig — creating ongoing operational funding sourced from the protocol's own code.",
      },
      {
        label: "AGENCIES & CONSULTANCIES",
        headline: "Every client repository, a revenue stream.",
        body: "Agencies managing client codebases can co-sign instruments and split settlement between the client's domain and the agency's domain — compensation structurally tied to the health of the code delivered.",
      },
    ] as const,
  },
  closingCTA: {
    label: "GET STARTED",
    headlineLine1: "Connect the repository.",
    headlineLine2: "Capitalise the work.",
    sub:
      "Installation takes under two minutes. Issuance takes under five. Yield begins accruing at the next block.",
    ctaPrimary: "Connect GitHub",
    ctaSecondary: "$ npm i @etherbonds/sdk",
    footnote: "No credit card · No custody · Non-custodial by protocol design",
  },
} as const;
